server:
  port: 9003
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/sogeti;AUTO_SERVER=TRUE
    username: sa
    password:
    initialize: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  allowed:
    resources: /h2-console/**